# Generated by Django 5.1.2 on 2024-10-22 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='negocio',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='negocio',
        ),
    ]
