# Generated by Django 5.1.2 on 2024-10-28 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='additional_description',
        ),
        migrations.AlterField(
            model_name='license',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 15, 53, 37, 833139, tzinfo=datetime.timezone.utc)),
        ),
    ]
