# Generated by Django 5.1.2 on 2024-10-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_category_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, default='Otros', max_length=100, null=True),
        ),
    ]
