# Generated by Django 5.1.2 on 2024-11-03 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_business_is_public_product_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.card'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.card'),
        ),
        migrations.AddField(
            model_name='sale',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.card'),
        ),
    ]
