# Generated by Django 5.1.2 on 2024-11-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_expense_card_purchase_card_sale_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='plan',
            field=models.CharField(choices=[('gratis', 'Gratis'), ('basico', 'Básico'), ('pro', 'Pro')], default='gratis', max_length=10),
        ),
    ]
