# Generated by Django 5.1.2 on 2024-10-28 22:52

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_license_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='expiration_date',
            field=models.DateTimeField(default=api.models.get_expiration_date),
        ),
    ]
