# Generated by Django 5.1.2 on 2024-10-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_business_image_contact_image_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='debt',
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_credit',
            field=models.BooleanField(default=False),
        ),
    ]
