# Generated by Django 5.1.2 on 2024-11-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_product_price_product_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='phone',
            field=models.CharField(blank=True, default='No especificado', max_length=15, null=True),
        ),
    ]
