# Generated by Django 5.1.2 on 2024-10-28 02:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 3, 4, 3, 33061, tzinfo=datetime.timezone.utc)),
        ),
    ]
