# Generated by Django 5.1.2 on 2024-11-13 13:10

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_product_stock_product_stock_non_negative'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(default=api.models.generate_order_code, editable=False, max_length=8, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=15)),
                ('delivery_type', models.CharField(choices=[('pickup', 'Recoger en tienda'), ('delivery', 'Entrega a domicilio')], max_length=10)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('delivery_municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_notes', models.TextField(blank=True, null=True)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('preparing', 'En preparación'), ('ready', 'Listo para entrega/recogida'), ('in_delivery', 'En camino'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.business')),
            ],
        ),
    ]
