# Generated by Django 5.1.2 on 2024-11-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_order_created_at_order_total_amount_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_notes',
            field=models.TextField(blank=True, help_text='Notas sobre el cambio de estado del pedido', null=True),
        ),
    ]
