# Generated by Django 5.1.2 on 2024-11-15 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_order_status_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('does_delivery', models.BooleanField(default=True, verbose_name='Realiza Entregas a Domicilio')),
                ('delivery_zones', models.JSONField(default=dict, help_text='Zonas de entrega y sus precios. Formato: {"zona": precio}')),
                ('business_hours', models.JSONField(default=dict, help_text='Horario de atención por día')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('telegram_user', models.CharField(blank=True, max_length=50, null=True, verbose_name='Usuario de Telegram')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='api.business')),
            ],
            options={
                'verbose_name': 'Ajustes del Negocio',
                'verbose_name_plural': 'Ajustes de Negocios',
            },
        ),
    ]
