# Generated by Django 5.1.2 on 2024-11-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_businesssettings_theme_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesssettings',
            options={'verbose_name': 'Configuración de negocio', 'verbose_name_plural': 'Configuraciones de negocios'},
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='secondary_color',
            field=models.CharField(default='#4F46E5', max_length=7),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='use_gradient',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='business_hours',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='delivery_zones',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='does_delivery',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='telegram_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='theme_color',
            field=models.CharField(default='#4F46E5', max_length=7),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
