# Generated by Django 5.1.2 on 2024-11-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_businesssettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='banner_text',
            field=models.CharField(default='¡Bienvenido a nuestro negocio!', max_length=100),
        ),
    ]
