# Generated by Django 5.1.2 on 2024-11-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_businesssettings_banner_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_buisiness',
            field=models.BooleanField(default=False),
        ),
    ]
