# Generated by Django 5.1.2 on 2024-11-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_businesssettings_banner_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.AddField(
            model_name='purchase',
            name='Product',
            field=models.ManyToManyField(to='api.product'),
        ),
        migrations.AddField(
            model_name='sale',
            name='Product',
            field=models.ManyToManyField(to='api.product'),
        ),
    ]
