# Generated by Django 5.1.2 on 2024-11-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_card_is_buisiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='is_buisiness',
            field=models.BooleanField(default=True),
        ),
    ]
