# Generated by Django 5.1.2 on 2024-11-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_card_is_buisiness'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='is_buisiness',
            new_name='is_business',
        ),
    ]
